// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
........ccccc...................
......ccbbbbbc..................
....ccddbbbbbbf.................
...cbbbddbbffbf.................
....ffffdbbffbff................
.......fbbbbbbbf................
.......fbbbbbbbff...............
......ffbbbbbbbbfff.............
......f6bbbbbb663ddcc...........
.....cc66bbbb666dddddc..........
.....cd36666663dddddddc.........
.....cddd3333dbddddddbcc........
.....cddddddddbdddddbbddc.......
.....cddddddddbbdddbbdddbc......
......cddddddddbbdbbddddbbccc...
......ccddddddddbbbbcccccbbbcc..
.......ccddddddddddddddbccffff..
........cccbddccbddddbbfff......
........c333bb333cbbfff.........
........c33cc33cc3fff...........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
